# Generated by Django 5.2.8 on 2025-11-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
