# Generated by Django 5.2.8 on 2025-12-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_productmodel_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.CharField(max_length=150),
        ),
    ]
