# Generated by Django 5.2.8 on 2025-12-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_productmodel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.CharField(max_length=200),
        ),
    ]
