# Generated by Django 5.2.8 on 2025-12-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_productmodel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='bottom_sizes_available',
            field=models.CharField(blank=True, help_text='Comma separated BOTTOM sizes e.g. 26,28,30,32 OR S,M,L', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='top_sizes_available',
            field=models.CharField(blank=True, help_text='Comma separated TOP sizes e.g. XS,S,M,L', max_length=100, null=True),
        ),
    ]
