# Generated by Django 5.2.8 on 2025-12-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='product',
        ),
        migrations.DeleteModel(
            name='PaymentModel',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItemModel',
        ),
    ]
