# Generated by Django 5.2.8 on 2025-12-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='bottom_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='top_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
