# Generated by Django 5.2.8 on 2025-11-21 11:20

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('body_shape', models.CharField(blank=True, choices=[('hourglass', 'Hourglass'), ('pear', 'Pear Shape'), ('apple', 'Apple Shape'), ('rectangle', 'Rectangle'), ('inverter_triangle', 'Inverted Triangle'), ('diamond', 'Diamond Shape'), ('oval', 'Oval/Round')], max_length=100, null=True)),
                ('preferred_size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL'), ('4XL', '4XL')], max_length=15, null=True)),
                ('style_preference', models.CharField(blank=True, choices=[('casual', 'Casual'), ('office', 'Office Wear'), ('party', 'Party Wear'), ('ethnic', 'Ethnic Wear'), ('sports', 'Sportswear')], max_length=100, null=True)),
                ('favorite_color', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
